set_property PACKAGE_PIN U19 [get_ports {Out[2]}]
set_property PACKAGE_PIN V19 [get_ports {Out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[0]}]
set_property PACKAGE_PIN V17 [get_ports updown]
set_property PACKAGE_PIN W19 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports updown]
set_property PACKAGE_PIN T17 [get_ports clock]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clock_IBUF]

set_property PACKAGE_PIN W4 [get_ports {Anode[3]}]
set_property PACKAGE_PIN V4 [get_ports {Anode[2]}]
set_property PACKAGE_PIN U4 [get_ports {Anode[1]}]
set_property PACKAGE_PIN U2 [get_ports {Anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[0]}]
set_property PACKAGE_PIN W7 [get_ports {SSD[6]}]
set_property PACKAGE_PIN W6 [get_ports {SSD[5]}]
set_property PACKAGE_PIN U8 [get_ports {SSD[4]}]
set_property PACKAGE_PIN V8 [get_ports {SSD[3]}]


set_property PACKAGE_PIN U5 [get_ports {SSD[2]}]
set_property PACKAGE_PIN V5 [get_ports {SSD[1]}]
set_property PACKAGE_PIN U7 [get_ports {SSD[0]}]

set_property PACKAGE_PIN E19 [get_ports {Out[1]}]
set_property PACKAGE_PIN U16 [get_ports {Out[0]}]
